/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RaporlarRouteImport } from './routes/raporlar'
import { Route as MusteriTelefonBilgileriRouteImport } from './routes/musteri-telefon-bilgileri'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KullanicilarRouteImport } from './routes/kullanicilar'
import { Route as KisayollarRouteImport } from './routes/kisayollar'
import { Route as KartlarRouteImport } from './routes/kartlar'
import { Route as IslemlerRouteImport } from './routes/islemler'
import { Route as DuyurularRouteImport } from './routes/duyurular'
import { Route as DijitalBankacilikDashboardRouteImport } from './routes/dijital-bankacilik-dashboard'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BankacilikLoglariRouteImport } from './routes/bankacilik-loglari'
import { Route as AyarlarRouteImport } from './routes/ayarlar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'

const RaporlarRoute = RaporlarRouteImport.update({
  id: '/raporlar',
  path: '/raporlar',
  getParentRoute: () => rootRouteImport,
} as any)
const MusteriTelefonBilgileriRoute = MusteriTelefonBilgileriRouteImport.update({
  id: '/musteri-telefon-bilgileri',
  path: '/musteri-telefon-bilgileri',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KullanicilarRoute = KullanicilarRouteImport.update({
  id: '/kullanicilar',
  path: '/kullanicilar',
  getParentRoute: () => rootRouteImport,
} as any)
const KisayollarRoute = KisayollarRouteImport.update({
  id: '/kisayollar',
  path: '/kisayollar',
  getParentRoute: () => rootRouteImport,
} as any)
const KartlarRoute = KartlarRouteImport.update({
  id: '/kartlar',
  path: '/kartlar',
  getParentRoute: () => rootRouteImport,
} as any)
const IslemlerRoute = IslemlerRouteImport.update({
  id: '/islemler',
  path: '/islemler',
  getParentRoute: () => rootRouteImport,
} as any)
const DuyurularRoute = DuyurularRouteImport.update({
  id: '/duyurular',
  path: '/duyurular',
  getParentRoute: () => rootRouteImport,
} as any)
const DijitalBankacilikDashboardRoute =
  DijitalBankacilikDashboardRouteImport.update({
    id: '/dijital-bankacilik-dashboard',
    path: '/dijital-bankacilik-dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BankacilikLoglariRoute = BankacilikLoglariRouteImport.update({
  id: '/bankacilik-loglari',
  path: '/bankacilik-loglari',
  getParentRoute: () => rootRouteImport,
} as any)
const AyarlarRoute = AyarlarRouteImport.update({
  id: '/ayarlar',
  path: '/ayarlar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ayarlar': typeof AyarlarRoute
  '/bankacilik-loglari': typeof BankacilikLoglariRoute
  '/dashboard': typeof DashboardRoute
  '/dijital-bankacilik-dashboard': typeof DijitalBankacilikDashboardRoute
  '/duyurular': typeof DuyurularRoute
  '/islemler': typeof IslemlerRoute
  '/kartlar': typeof KartlarRoute
  '/kisayollar': typeof KisayollarRoute
  '/kullanicilar': typeof KullanicilarRoute
  '/login': typeof LoginRoute
  '/musteri-telefon-bilgileri': typeof MusteriTelefonBilgileriRoute
  '/raporlar': typeof RaporlarRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ayarlar': typeof AyarlarRoute
  '/bankacilik-loglari': typeof BankacilikLoglariRoute
  '/dashboard': typeof DashboardRoute
  '/dijital-bankacilik-dashboard': typeof DijitalBankacilikDashboardRoute
  '/duyurular': typeof DuyurularRoute
  '/islemler': typeof IslemlerRoute
  '/kartlar': typeof KartlarRoute
  '/kisayollar': typeof KisayollarRoute
  '/kullanicilar': typeof KullanicilarRoute
  '/login': typeof LoginRoute
  '/musteri-telefon-bilgileri': typeof MusteriTelefonBilgileriRoute
  '/raporlar': typeof RaporlarRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ayarlar': typeof AyarlarRoute
  '/bankacilik-loglari': typeof BankacilikLoglariRoute
  '/dashboard': typeof DashboardRoute
  '/dijital-bankacilik-dashboard': typeof DijitalBankacilikDashboardRoute
  '/duyurular': typeof DuyurularRoute
  '/islemler': typeof IslemlerRoute
  '/kartlar': typeof KartlarRoute
  '/kisayollar': typeof KisayollarRoute
  '/kullanicilar': typeof KullanicilarRoute
  '/login': typeof LoginRoute
  '/musteri-telefon-bilgileri': typeof MusteriTelefonBilgileriRoute
  '/raporlar': typeof RaporlarRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ayarlar'
    | '/bankacilik-loglari'
    | '/dashboard'
    | '/dijital-bankacilik-dashboard'
    | '/duyurular'
    | '/islemler'
    | '/kartlar'
    | '/kisayollar'
    | '/kullanicilar'
    | '/login'
    | '/musteri-telefon-bilgileri'
    | '/raporlar'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ayarlar'
    | '/bankacilik-loglari'
    | '/dashboard'
    | '/dijital-bankacilik-dashboard'
    | '/duyurular'
    | '/islemler'
    | '/kartlar'
    | '/kisayollar'
    | '/kullanicilar'
    | '/login'
    | '/musteri-telefon-bilgileri'
    | '/raporlar'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/form/address'
    | '/demo/form/simple'
  id:
    | '__root__'
    | '/'
    | '/ayarlar'
    | '/bankacilik-loglari'
    | '/dashboard'
    | '/dijital-bankacilik-dashboard'
    | '/duyurular'
    | '/islemler'
    | '/kartlar'
    | '/kisayollar'
    | '/kullanicilar'
    | '/login'
    | '/musteri-telefon-bilgileri'
    | '/raporlar'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AyarlarRoute: typeof AyarlarRoute
  BankacilikLoglariRoute: typeof BankacilikLoglariRoute
  DashboardRoute: typeof DashboardRoute
  DijitalBankacilikDashboardRoute: typeof DijitalBankacilikDashboardRoute
  DuyurularRoute: typeof DuyurularRoute
  IslemlerRoute: typeof IslemlerRoute
  KartlarRoute: typeof KartlarRoute
  KisayollarRoute: typeof KisayollarRoute
  KullanicilarRoute: typeof KullanicilarRoute
  LoginRoute: typeof LoginRoute
  MusteriTelefonBilgileriRoute: typeof MusteriTelefonBilgileriRoute
  RaporlarRoute: typeof RaporlarRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/raporlar': {
      id: '/raporlar'
      path: '/raporlar'
      fullPath: '/raporlar'
      preLoaderRoute: typeof RaporlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musteri-telefon-bilgileri': {
      id: '/musteri-telefon-bilgileri'
      path: '/musteri-telefon-bilgileri'
      fullPath: '/musteri-telefon-bilgileri'
      preLoaderRoute: typeof MusteriTelefonBilgileriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kullanicilar': {
      id: '/kullanicilar'
      path: '/kullanicilar'
      fullPath: '/kullanicilar'
      preLoaderRoute: typeof KullanicilarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kisayollar': {
      id: '/kisayollar'
      path: '/kisayollar'
      fullPath: '/kisayollar'
      preLoaderRoute: typeof KisayollarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kartlar': {
      id: '/kartlar'
      path: '/kartlar'
      fullPath: '/kartlar'
      preLoaderRoute: typeof KartlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/islemler': {
      id: '/islemler'
      path: '/islemler'
      fullPath: '/islemler'
      preLoaderRoute: typeof IslemlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duyurular': {
      id: '/duyurular'
      path: '/duyurular'
      fullPath: '/duyurular'
      preLoaderRoute: typeof DuyurularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dijital-bankacilik-dashboard': {
      id: '/dijital-bankacilik-dashboard'
      path: '/dijital-bankacilik-dashboard'
      fullPath: '/dijital-bankacilik-dashboard'
      preLoaderRoute: typeof DijitalBankacilikDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bankacilik-loglari': {
      id: '/bankacilik-loglari'
      path: '/bankacilik-loglari'
      fullPath: '/bankacilik-loglari'
      preLoaderRoute: typeof BankacilikLoglariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayarlar': {
      id: '/ayarlar'
      path: '/ayarlar'
      fullPath: '/ayarlar'
      preLoaderRoute: typeof AyarlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AyarlarRoute: AyarlarRoute,
  BankacilikLoglariRoute: BankacilikLoglariRoute,
  DashboardRoute: DashboardRoute,
  DijitalBankacilikDashboardRoute: DijitalBankacilikDashboardRoute,
  DuyurularRoute: DuyurularRoute,
  IslemlerRoute: IslemlerRoute,
  KartlarRoute: KartlarRoute,
  KisayollarRoute: KisayollarRoute,
  KullanicilarRoute: KullanicilarRoute,
  LoginRoute: LoginRoute,
  MusteriTelefonBilgileriRoute: MusteriTelefonBilgileriRoute,
  RaporlarRoute: RaporlarRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
